# -*- coding: utf-8 -*-
"""Atividade 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A9tvXh2TeUfGWmENE20jRM5No8DsYLDE
"""

#problema 1
x = float(input("Valor de X: "))
y = float(input("Valor de Y: "))

def fun(x,y):
  if x >= 0 and y >= 0:
    z = x + y
  elif x >= 0 and y < 0:
    z = x + y**2
  elif x < 0 and y >= 0:
    z = x**2 + y
  elif x < 0 and y < 0:
    z = x**2 + x**2
  return z

fun(x,y)

#problema 2
#np.var // np.std
import numpy as np

pos = int(input("Quantidade de posições do vetor: "))
x = []

for k in range(pos):
  x.append(float(input("Valor da Posição %d: " %k)))

def vetor(x):
  var = np.var(x)
  dp = np.std(x)
  print("Variância: %.2f Desvio Padrão: %.2f" %(var,dp))

vetor(x)

#problem 3

n = int(input("Verificar o número: "))

matriz = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]

def verify(matriz):
  for l in range(4):
    for c in range(3):
      if n == matriz[l][c]:
        print("O valor se encontra na matriz")
      elif (l==3 and c==2) and (n not in matriz):
        print("O valor não se encontra na matriz")

verify(matriz)

#problema 4

lista = [1,4,2,3,4,2,3,4]

def repeated(lista):
  rep = []
  for i in range(len(lista)):
    if lista.index(lista[i]) != i:
      if lista[i] not in rep:
        rep.append(lista[i])
  return sorted(rep)

repeated(lista)