# -*- coding: utf-8 -*-
"""Atividade 4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MZFGkkT0KoxZrXgT_UkB49TKtZW33A3n
"""

#problema 1
tabela = { 10 : "Ana",
           15 : "Lucas",
           13 : "Bia",
           24 : "Larissa",
           21 : "Leo",
           32 : "Bruno",
           4 : "Cássio",
           8 : "Jonas",
           23 : "Lauro",
           18 : "Mateus" }

sort = sorted(tabela.keys())
print(tabela[sort[0]],"de", sort[0],"anos de idade")

#problem 2

###### CORRIDA ##########

#Tempos dos corredores:
import random as rd

tempo = []

for i in range(60):
  volta = rd.randint(120,180)
  tempo.append(volta)

#Matriz dos Tempos com os nomes:

line = [0] * 6
matriz = [line] * 10

pilotos = []
media = []

for l in range(6):
  line = []
  pilot = str(input("Nome do piloto %d:  " %(l + 1)))
  for c in range(10):
    if l == 0:
      line.append(tempo[c])
      if c > 8:
        pilotos.append(pilot)
        x = (sum(line))/10
        media.append(x)
    elif l == 1:
      line.append(tempo[c + 10])
      if c > 8:
        pilotos.append(pilot)
        x = (sum(line))/10
        media.append(x)
    elif l == 2:
      line.append(tempo[c + 20])
      if c > 8:
        pilotos.append(pilot)
        x = (sum(line))/10
        media.append(x)
    elif l == 3:
      line.append(tempo[c + 30])
      if c > 8:
        pilotos.append(pilot)
        x = (sum(line))/10
        media.append(x)
    elif l == 4:
      line.append(tempo[c + 40])
      if c > 8:
        pilotos.append(pilot)
        x = (sum(line))/10
        media.append(x)
    elif l == 5:
      line.append(tempo[c + 50])
      if c > 8:
        pilotos.append(pilot)
        x = (sum(line))/10
        media.append(x)
  matriz[l] = line

#########RESULTADOS#############

#menor tempo:

y = min(tempo)
for i in range(6):
  if y in matriz[i]:
    print("Menor tempo foi: ", y, "Feito por: ", pilotos[i], "na volta: ", tempo.index(y), sep='\n')

#menor média:

m = min(media)
print("A melhor média foi: ", m, "Feito pelo piloto: ", pilotos[media.index(m)], sep='\n')

#####display#######

print("==Todos os Resultados==")

for r in range(6):
  x = min(matriz[r])
  print(pilotos[r], "tempos:", matriz[r], '\n', "média:", media[r], '\n',"melhor tempo:", x)