# -*- coding: utf-8 -*-
"""exercicios layse.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x5NquPbFfda0PDOX-QnxPklyue5q20Wg
"""

#ex1: Elevador
max = float(input("Qual a capacidade do elevador(em kilos)? "))
n = int(input("Quantas pessoas estão no elevador? "))
lista = []
for i in range(n):
  kg = float(input("Peso da Pessoa %d: " %(i+1)))
  lista.append(kg)
if sum(lista) > max:
  print("O elevador não está liberado")
else:
  print("Elevador Liberado")

#ex2: Tabuada
n = int(input("Informe o Número: "))
cont = 1
while cont <= 10:
  print(n, "x", cont, "=", n * cont)
  cont = cont + 1

#ex3: Notas
nota = float(input("Nota do Aluno: "))
lista = []

print("quando finalizar a digitação dos dados, escreva: 11 ou -1")

#digitação das notas
while 0 <= nota <= 10:
  lista.append(nota)
  nota = float(input("Nota do Aluno: "))

#cálculo da média
media = sum(lista)/len(lista)
print(round(media + 0.5))

#ex4: Contador
cont = -20
while cont <= 16:
  print(cont)
  cont = cont + 1
#ou (pra rir fessora)
print("De -20 a 16")

#ex5: Intervalo
vi = int(input("Valor Inicial: "))
vf = int(input("Valor Final: "))
sequence = []

if vi < vf:
  print("Sequência Válida")
  while vi < vf:
    vi = vi + 1
    sequence.append(vi)
  sequence.reverse()
  sequence.pop(0)
elif vi > vf:
  print("Sequência Válida")
  while vi > vf:
    vi = vi - 1
    sequence.append(vi)
  sequence.reverse()
  sequence.pop(0)
else:
  print("Sequência Inválida")

print(sequence)

#ex6: Tabuada com for
n = int(input("Informe o Número: "))

for i in range(1,11):
  x = n * i
  print(n, "x", i, "=", x)

# Commented out IPython magic to ensure Python compatibility.
#ex7: Soma e média
n = int(input("Quantos Números vamos calcular? "))
lista = []

for i in range(n):
  x = float(input("Número %d: " %(i+1)))
  lista.append(x)

soma = sum(lista)
media = (sum(lista))/n

print("""Soma:
# %.2f
Média Aritmética:
# %.2f """ %(soma,media))

#ex8: Agenda (15 em 15 min)

for hora in range(24):
  for minuto in range(0,60,15):
    print("%d:%d" %(hora,minuto))