# -*- coding: utf-8 -*-
"""APS2_UII_N02_Filipe_Andrade_Nascimento.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n5c98EB8I4X9K-1_etm5M5TplwKtRxiB
"""

import random as rd

par,impar = 0,0
for i in range(15):
  friend_1 = rd.randint(0,10)
  friend_2 = rd.randint(0,10)
  total = friend_1 + friend_2
  if total % 2 == 0:
    par += 1
  else:
    impar += 1

if par > impar:
  print("Amigo 1 Ganha com %d pontos" %par)
else:
  print("Amigo 2 ganha com %d pontos" %impar)