# -*- coding: utf-8 -*-
"""APS_UII_N02_Filipe_Andrade_Nascimento.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NCizLTP5GSLHPNEMEB8QJ-KlWrwBGz9V
"""

import random as rd

game =  { 0 : "Pedra",
          1 : "Papel",
          2 : "Tesoura" }

user = int(input("Pedra(0), Papel(1), Tesoura(2)?"))
print("Escolha do usuário:", game[user])

computer = rd.randint(0,2)
print("Escolha do pc:", game[computer])

if (game[user] == "Pedra" and game[computer] == "Tesoura") or (game[user] == "Papel" and game[computer] == "Pedra") or (game[user] == "Tesoura" and game[computer] == "Papel"):
  print("User Wins")
elif game[user] == game[computer]:
  print("Empate")
else:
  print("Computer Wins")