# -*- coding: utf-8 -*-
"""Matrizes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/110tf1Yhq_pecInsB_t_NEbY_lbYuKvjs
"""

line = [0] * 3
matrix = [line] * 3

for i in range(3):
  line = []
  for j in range(3):
    x = int(input("Digite o elemento da linha %d coluna %d: " %(i,j)))
    line.append(x)

  matrix[i] = line

print(matrix)