# -*- coding: utf-8 -*-
"""Prova_N02_Filipe_Andrade_Nascimento.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bS6TPhrDBW4RIGC78LXNkwB1MX8DanrE
"""

#questão 1:

print("""
Deixe a sua opinião sobre o Espetáculo:
ótimo = *****
bom = ****
regular = ***
ruim = **
péssimo = * 
""")

todas_opinioes = []
idade_otimo = []
idade_ruim = []

for k in range(30):
   cpf = str(input("CPF: "))
   nome = str(input("Nome: "))
   idade = int(input("Idade: "))
   sexo = str(input("M para Masculino; F para Feminino: "))
   opinion = str(input("Qual a sua opinião sobre o espetáculo? "))
   todas_opinioes.append(opinion)
   if opinion == "*****":
     idade_otimo.append(idade)
   elif opinion == "**":
     idade_ruim.append(idade)


otimo = 0
bom = 0
regular = 0
ruim = 0
pessimo = 0
for enumerate in todas_opinioes:
  if enumerate == "*****":
    otimo = otimo + 1
  elif enumerate == "****":
    bom = bom + 1
  elif enumerate == "***":
    regular = regular + 1
  elif enumerate == "**":
    ruim = ruim + 1
  else:
    pessimo = pessimo + 1

todas_opinioes = [otimo,bom,regular,ruim,pessimo]

otimo_stat = ((todas_opinioes[0])/sum(todas_opinioes)) * 100
bom_stat = ((todas_opinioes[1])/sum(todas_opinioes)) * 100
regular_stat = ((todas_opinioes[2])/sum(todas_opinioes)) * 100
diferenca_stat = bom_stat - regular_stat
diferenca_idade = (max(idade_otimo)) - (max(idade_ruim))

print("Percentual de Respostas 'Ótimo': ", round(otimo_stat,2),"%")
print("Diferença Percentual entre 'bom' e 'regular': ", diferenca_stat,"%")
print("Diferença de idade entre 'ótimo' e 'ruim': ", diferenca_idade)
print("Média de idade dos espectadores que responderam 'ruim': ", sum(idade_ruim)/len(idade_ruim))

#questão 2:
numero_pessoas = int(input("Quantidade de pessoas:"))
salary = []
age = []
women = 0

for i in range(numero_pessoas):
  cpf = str(input("CPF: "))
  nome = str(input("nome: "))
  sexo = str(input("M para Masculino; F para Feminino: "))
  idade = int(input("Idade: "))
  salario = int(input("Salário: "))
  salary.append(salario)
  age.append(idade)
  if (sexo == "F") and (salario <= 1200):
    women = women + 1

media = sum(salary)/numero_pessoas

print("Média de Salário do grupo: ", round(media,2))
print("""Menor idade: %d
Maior idade: %d"""%(min(age),max(age)))
print("Mulheres com Salário até R$1200,00: ", women)

#questão 3:

x = 60
y = 35
y += float(x)

print(x)
print(y)