# -*- coding: utf-8 -*-
"""Filipe Andrade Nascimento - respostas_atividade_07.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bQ-8508Kw0vWtwlmv7oJCG9P1WJ1cv0p
"""

"""bibliotecas necessárias"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

from google.colab import files 
import io

"""Função que vai abrir os arquivos e importar para o nosso programa"""
"""UPLOAD_LOJA(resultados_avaliacao)"""

uploaded = files.upload()
arquivo = next(iter(uploaded))

gfile_name = io.StringIO(uploaded[arquivo].decode('ISO 8859-1').strip())
dados = pd.read_csv(gfile_name,sep=';')

print(dados.columns.ravel())

"""**INTEGRANTES DO GRUPO:**

---


"""

#PROBLEMA 1.1:
df_loja = pd.DataFrame(dados)
freq = df_loja.groupby('INDICADOR')['INDICADOR'].count()
freq

#PROBLEMA 1.2:
sns.set_theme(style="darkgrid", palette="mako")
h_bar_graph = sns.countplot(data=df_loja, y=df_loja['INDICADOR'])

"""UPLOAD_IRIS(dataset_iris)"""
uploaded = files.upload()
arquivo = next(iter(uploaded))

gfile_name = io.StringIO(uploaded[arquivo].decode('ISO 8859-1').strip())
dados_iris = pd.read_csv(gfile_name,sep=';')

print(dados.columns.ravel())

#PROBLEMA 2.1:
df_iris = pd.DataFrame(dados_iris)
sns.set_theme(style="whitegrid", palette="deep")
sns.displot(data=df_iris, x="petal_length", hue="tipo", kind="kde")

#PROBLEMA 2.2:
#como a coluna sepal_lenght está vazia, fiz com sepal_width
sns.set_theme(style="whitegrid", palette="deep")
sns.displot(data=df_iris, x="sepal_width", hue="tipo", kind="kde")